server:
  port: 9192
spring:
  zipkin:
    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
  application:
    name: order-service
logging:
  file: I:/latest/sts-4.27.0_workspace/logs/order/oms.log

